[setup]
commands = [
  "python -m venv --copies /opt/venv",
  ". /opt/venv/bin/activate",
  "pip install -r requirements.txt"
]

[start]
cmd = "daphne admin.asgi:application --port $PORT --bind 0.0.0.0"
