# Generated by Django 5.1 on 2024-08-16 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dep', models.CharField(max_length=50)),
                ('branch', models.CharField(max_length=10)),
                ('roll_no', models.IntegerField()),
                ('enr_no', models.BigIntegerField()),
                ('batch', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
