# Generated by Django 5.1 on 2024-08-25 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_votes_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='upvotes',
            field=models.BigIntegerField(default=0),
        ),
    ]
