# Generated by Django 5.1 on 2024-08-28 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_chatgroup_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatgroup',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
